/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'timeslot' : string,
  'status' : string,
  'studentName' : string,
  'subject' : string,
  'date' : string,
  'createdAt' : bigint,
  'parentPhone' : string,
  'studentClass' : string,
  'parentName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAvailableSubjects' : ActorMethod<[string], Array<string>>,
  'getAvailableTimeslots' : ActorMethod<[], Array<string>>,
  'getBookingById' : ActorMethod<[bigint, string], Booking>,
  'getBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByParentPhone' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isTimeslotBookedForDate' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];