/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'timeslot' : IDL.Text,
  'status' : IDL.Text,
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'parentPhone' : IDL.Text,
  'studentClass' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAvailableSubjects' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getAvailableTimeslots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat, IDL.Text], [Booking], ['query']),
  'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByParentPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isTimeslotBookedForDate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'timeslot' : IDL.Text,
    'status' : IDL.Text,
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'parentPhone' : IDL.Text,
    'studentClass' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAvailableSubjects' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAvailableTimeslots' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat, IDL.Text], [Booking], ['query']),
    'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByParentPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isTimeslotBookedForDate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };